{
 "title": "ESP32 Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "device",
    "query": "label_values(esp32_uptime, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "esp32_uptime{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Boot counter",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "esp32_boot_counter{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "esp32_temperature{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "format": "dtdurationms",
   "valueName": "current",
   "targets": [
    {
     "expr": "esp32_uptime{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "WiFi RSSI",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "esp32_wifi_rssi{instance=\"$instance\"} * -1"
    }
   ]
  },
  {
   "title": "Free heap",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "esp32_free_heap{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Graphics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "esp32_temperature{instance=\"$instance\"}",
     "legendFormat": "temperature"
    }
   ]
  },
  {
   "title": "WiFi RSSI",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "esp32_wifi_rssi{instance=\"$instance\"} * -1",
     "legendFormat": "rssi"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "esp32_heap_size{instance=\"$instance\"}",
     "legendFormat": "heap_size"
    },
    {
     "expr": "esp32_free_heap{instance=\"$instance\"}",
     "legendFormat": "free_heap"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Flash",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "esp32_flash_size{instance=\"$instance\"}",
     "legendFormat": "flash_size"
    },
    {
     "expr": "esp32_available_size{instance=\"$instance\"}",
     "legendFormat": "available_size"
    }
   ]
  }
 ]
}