services:
  frontend:
    build:
      context: ./pwa
      args:
        REACT_APP_API_MINION_TOKEN: ${REACT_APP_API_MINION_TOKEN}
        REACT_APP_URL: ${REACT_APP_URL}
    container_name: minion_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
