; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform                    = espressif8266
board                       = nodemcuv2
framework                   = arduino
upload_port                 = COM3
monitor_port                = COM3
monitor_speed               = 115200
upload_speed                = 115200
upload_resetmethod          = nodemcu
board_build.filesystem      = littlefs
board_build.filesystem_size = 1m
monitor_filters             = esp8266_exception_decoder

platform_packages =
    tool-esptoolpy @ https://github.com/tasmota/esptool/releases/download/v4.7.0/esptool-4.7.0.zip

lib_deps =
    https://github.com/mathieucarbou/ESPAsyncWebServer/archive/refs/tags/v3.1.4.zip
    suculent/AESLib @ ^2.0.0
    ayushsharma82/ElegantOTA
    bblanchon/ArduinoJson
    arduino-libraries/NTPClient
    ThingPulse/ESP8266 and ESP32 OLED driver for SSD1306 displays
    xreef/EMailSender
    adafruit/Adafruit Unified Sensor
    adafruit/DHT sensor library
    adafruit/Adafruit MQTT Library
    https://github.com/Jockey-Repos/ArduinoUtilsCds.git

lib_ignore =
    AsyncTCP_RP2040W
    LittleFS_esp32
    WiFi101
    WiFiNINA_-_Adafruit_Fork
    WiFiNINA

build_flags =
    -D DEBUG
    -D USE_CRYPTO
    -D USE_OLED
    -D USE_MQTT
    -D USE_TEMPERATURE
    -D USE_SDCARD
    -D SERIAL_BAUD=115200
    -D MAX_PATH=256
    -D HTTP_REST_PORT=80
    -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
    -D AES_KEY_HEX='"000102030405060708090A0B0C0D0E0F"'
    -D AES_IV_HEX='"A0A1A2A3A4A5A6A7A8A9AAABACADAEAF"'
    -I "$PROJECT_INCLUDE_DIR"
    -D DEBUG_OUTPUT=Serial

build_src_filter =
    +<*>