; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:upesy_wroom]
platform        = espressif32
board           = upesy_wroom
framework       = arduino
upload_port     = COM3
monitor_port    = COM3
monitor_speed   = 115200
upload_resetmethod = nodemcu                ; reset automático após upload
board_build.filesystem = littlefs           ; Filesystem: LittleFS — substitui o container Docker mkspiffs do original
board_build.partitions = default_8MB.csv    ; Partição com 1 MB para o filesystem (equivalente ao -s 0x100000 do mkspiffs)
monitor_filters = esp32_exception_decoder

lib_deps =    
    https://github.com/ESP32Async/AsyncTCP.git
    https://github.com/mathieucarbou/ESPAsyncWebServer/archive/refs/tags/v3.1.4.zip
    rweather/Crypto @ ^0.4.0
    ayushsharma82/ElegantOTA
    sparkfun/SparkFun u-blox GNSS Arduino Library
    sandeepmistry/LoRa
    bblanchon/ArduinoJson
    suculent/AESLib
    arduino-libraries/NTPClient
    ThingPulse/ESP8266 and ESP32 OLED driver for SSD1306 displays
    https://github.com/Jockey-Repos/ArduinoUtilsCds.git

lib_ignore =
    WiFiNINA
    AsyncTCP_RP2040W
    LittleFS_esp32
    WiFi101

build_flags =
    -D DEBUG
    -D USE_CRYPTO
    -D USE_OLED
    -D USE_MQTT
    -D USE_TEMPERATURE
    -D USE_SDCARD
    -D USE_AUDIO
    -D SERIAL_BAUD=115200    
    -D MAX_PATH=256
    -D HTTP_REST_PORT=80
    -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
    -D AES_KEY_HEX='"000102030405060708090A0B0C0D0E0F"'
    -D AES_IV_HEX='"A0A1A2A3A4A5A6A7A8A9AAABACADAEAF"'
    -I "$PROJECT_INCLUDE_DIR"
    -I "$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/AsyncUDP/src"    
    -D DEBUG_OUTPUT=Serial
    -D CORE_DEBUG_LEVEL=0

build_src_filter =
    +<*>

lib_extra_dirs =
    $PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/AsyncUDP
